# Generated by Django 4.2.3 on 2023-07-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='staus',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
