# Generated by Django 4.2.3 on 2023-07-20 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='staus',
            new_name='status',
        ),
    ]
