# Generated by Django 4.2.3 on 2023-07-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_staus_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.JSONField(default='{}'),
        ),
    ]
