# Generated by Django 4.2.3 on 2023-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
