# Generated by Django 4.2.3 on 2023-07-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
