# Generated by Django 4.2.3 on 2023-07-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarUrl',
            field=models.ImageField(blank=True, null=True, upload_to='user/media'),
        ),
    ]
