# Generated by Django 4.2.3 on 2023-07-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_avatarurl_remove_user_name_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarUrl',
            field=models.ImageField(null=True, upload_to='user/media'),
        ),
    ]
