# Generated by Django 4.2.3 on 2023-07-17 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
