# Generated by Django 4.2.3 on 2023-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True, default='자신을 소개해주세요 :)', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='닉네임', max_length=50, null=True),
        ),
    ]
